# Site settings
author: Eli Cusic
title: Developing Developer
header-img: img/home-bg.png
email: tntitans31@gmail.com
copyright_name: Eli Cusic
description: > # this means to ignore newlines until "baseurl:"
  A blog to document my progress as an aspiring developer
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  etcusic

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
